name: Bug report Mc Dev
description: Create a bug report
labels: [status: unverified, type: bug]
body:
  - type: markdown
    attributes:
      value: |
        DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.
  - type: input
    attributes:
      label: Minecraft Development for IntelliJ plugin version
    validations:
      required: true
  - type: input
    attributes:
      label: IntelliJ version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Target platform
      options:
        - Bukkit
        - Spigot
        - Paper
        - Sponge
        - Forge
        - Fabric
        - Architectury
        - LiteLoader
        - Velocity
        - BungeeCord
        - Waterfall
    validations:
      required: false
