name: Bug report Mc Dev
description: Create a bug report
labels: [status: unverified, type: bug]
body:
  - type: input
    attributes:
      label: Minecraft Development for IntelliJ plugin version
    validations:
      required: false
  - type: input
    attributes:
      label: IntelliJ version
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: false
