name: Bug report Mc Dev
description: Create a bug report
labels: [status: unverified, type: bug]
body:
  - type: markdown
    attributes:
      value: |
        DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.
  - type: input
    attributes:
      label: Minecraft Development for IntelliJ plugin version
    validations:
      required: true
  - type: input
    attributes:
      label: IntelliJ version
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Target platform
      options:
        - label: Bukkit
        - label: Spigot
        - label: Paper
        - label: Sponge
        - label: Forge
        - label: Fabric
        - label: Architectury
        - label: LiteLoader
        - label: Velocity
        - label: BungeeCord
        - label: Waterfall
    validations:
      required: false
