name: Proposition
description: Proposer une fonctionnalité ou un sujet pour la documentation 
labels: [proposal]
body:
  - type: dropdown
    attributes:
      label: Version
      options:
        - 1.17
    validations:
      required: true
  - type: textarea
    attributes:
      label: Destription de la fonctionnalité
      description: A clear and concise description of what the bug is.
    validations:
      required: true
